weather_code_dictionary = {
        0: "Clear sky",
        1: "Mainly clear", 
        2: "Partly cloudy", 
        3: "Overcast",
        45: "Fog", 
        48:	"Depositing rime fog",
        51: "Light Drizzle", 
        53: "Moderate Drizzle",
        55: "Dense Drizzle",
        56: "Light Freezing Drizzle", 
        57: "Dense Freezing Drizzle",
        61: "Rain",
        63: "Rain Slight",
        65: "Rain moderate and heavy intensity",
        66: "Freezing Rain",
        67:	"Freezing Rain: Light and heavy intensity",
        71: "Snow fall:Slight",
        73: "Snow fall: moderate",
        75:	"Snow fall: heavy intensity",
        77:	"Snow grains",
        80: "Rain showers slight",
        81: "Rain showers moderate",
        82:	"Rain showers violent",
        85: "Snow showers slight",
        86:	"Snow showers heavy",
        95:	"Thunderstorm: Slight or moderate",
        96: "Thunderstorm with slight hail",
        99: "Thunderstorm with heavy hail"
    }